version: "3.9"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATASTATION_SERVER_ADDRESS: "0.0.0.0"
    volumes:
      - /etc/datastation:/etc/datastation
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
